  version: '3'
    
  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    webscraper:
      build: ./webscraper
      entrypoint: /code/entrypoint.sh
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./webscraper:/code
      ports:
        - "8000:8000"
      env_file:
        - ./webscraper/.env.dev
      depends_on:
        - db
    celery:
      build: ./webscraper
      command: celery worker --app=webscraper --loglevel=info
      volumes:
        - ./webscraper:/code
      env_file:
        - ./webscraper/.env.dev
      depends_on:
        - webscraper
        - db
        - redis
    redis:
      image: redis:5-alpine
